* Hero to Zero, learning how to learn, teach and grow Clojure 
** /The Pitch/: (Subheadings are presently alternative pitches)
*** How can we best support the needs of Clojure learners? Imagine a future where a person interested in learning Clojure was presented with a menu of choices of learning paths, each leading to well defined learning outcomes and offering various 'on-ramps' for learners of varying skill levels, even, and especially, for learners completely new to programming. Imagine a future where every learner feels welcome and supported through supportive human relationships, from participation in users groups, educational co-ops, and especially one-on-one apprentice/mentor pairings. How can we place the needs of the learner above all else and grow Clojure to the scale of its full potential? Much progress has already been made, but what more can we do, together, to reach this goal?
*** I intend to foster an interactive conversation with my audience about how we can create stronger and more creative mentor/apprentice relationships in our growing community. The jumping off point would be my personal learning path of going from Hero to Zero. (Hero to Zero is a greatly overloaded term that is meaningful to me, but likely mysterious to others, so it will be a conversational thread wherein I can relay my personal experience of learning programming and Clojure.)
** Education: inspired from within
*** The power of relationships to fan our internal flame.
** My story: Hero to Zero 
*** My view of the essence of the web: Communication
** Defining roles, eschewing roles: All people are communicators
*** People are note machines! We are ...
*** Mentors are learners too.
*** Embracing the life-long learning mentality without being distracted by every shiny new thing.
** Learning Paths
*** Interstate vs back roads
*** Machine Readable Curricula and Defined Learning Outcomes
** Learning Methods
*** Project based learning vs theory & lecture
** Apprenticeship/Mentor Relationships
*** What are the wants, needs and aspirations of both apprentices and mentors?
**** Apprentices
***** Structured Struggle vs Defeated Exasperation.
***** (Source: [[https://www.farnamstreetblog.com/2013/01/how-people-learn/][How People Learn]]) Empathy/Understanding of Mentor that Learner doesn't possess rich mental model, or even capacity to organize rich mental model immediately. This is grown over time by ensuring that fundamental concepts are well understood. This should be the main objective, rather than conveying a deluge of facts, which have no meaningful place in the mind to be stored effectively.
**** Mentors
***** Support in achieving high impact community goals.
****** Tutorials, Videos, Books, Lectures, Experiments
****** Apprentice as Subject: One free of the 'Curse of Knowledge.'
*** How do we improve the lives of individuals in each group?
**** How can learners facilitate mentor's needs and wants?
**** How can mentors facilitate learner's needs and wants?
**** What tools, platforms and communication strategies exist or could exist to support these objectives?
** New paradigms for collaboration?
*** Open source & Commerce in Harmony
**** Constructive Capitalism and the Long Wave
*** Education/Marketing Co-ops
**** nownetworking.com
***** Please take my idea, I'm to busy to do all of them!
****** Disclaimer: Okay, not all my ideas :)
** Complex sugar obscuring simple Clojure fundamentals
*** How do we best de-complect Clojure's complexities from its simple core?
**** e.g. (Source: Russ Olsen) Russ helped me see that Namespaces were simply mappings of names to values but my learning of the subject was distracted by my instinct to tackle the complex aspects of Namespaces: symbols refer to vars, which refer to mutable storage locations, which contain values. These are too many incidental details to take on for a newcomer and distract from the fundamental simplicity of what Namespaces are about. It does, however, help to know that such incidental complexity has a purpose in Clojure, which is to keep unaware developers from shooting their toes off. This mentor related perspective helped me accept Clojure's complexity around Namespaces with more of an open mind, taking the sting out of it.

